### ISSUE TITLE
Error: cannot find `yo-yoify/lib/appendChild`, `on-load`

### ISSUE THREAD

**Issue by arturi** [goto-bus-stop/babel-plugin-yo-yoify#11]
This [happens on NPM v2, when used with browserify/babelify](https://travis-ci.org/transloadit/uppy/builds/205848228), my guess is it’s because of nested dependencies in NPM v2 vs flat in v3. Seems to be fixed by adding `yo-yoify` as devDependency alongside `babel-plugin-yo-yoify`, in the project where its used. Should we add a note to docs, and a peerDependency maybe? Please see https://github.com/novemberborn/babel-plugin-es6-promise/issues/19.

<img width="834" alt="screen shot 2017-02-27 at 12 20 40 pm" src="https://cloud.githubusercontent.com/assets/1199054/23373745/52751a08-fcef-11e6-9fea-9b169acf9c42.png">

**Comment by goto-bus-stop** [comment]
Yeah, a peerDependency+doc note sounds good. Thanks for the report :raised_hands:

(Plain `yo-yoify` does this by importing the full path using `require.resolve`, but we can't do that here since a babel plugin can also be used like `babel src --out-dir lib` and have the `lib` folder published to npm.)

**Comment by arturi** [comment]
Cool, thanks! 

> we can't do that here since a babel plugin can also be used like babel src --out-dir lib and have the lib folder published to npm

Yes, that’s exactly how I do it.

Seems to work for me without `on-load` with just `yo-yoify` for some reason: https://github.com/transloadit/uppy/pull/165/commits/037b64b475fe5792492dbc69cf94595142a3e5fc. I guess because `yo-yoify` installs `on-load` as a dependency by itself. Also moved it to `devDependency` and it works as well, though not sure its correct.

**Comment by goto-bus-stop** [comment]
> Also moved it to devDependency and it works as well, though not sure its correct.

The `on-load` and `yo-yoify/lib/appendChild` modules need to be available when the bundle is being created, so if third parties are going to be bundling your library you'll need them as normal dependencies. if you publish a prebuilt browserified/webpacked/rolluped package devDependencies is fine.

**Comment by goto-bus-stop** [comment]
> Seems to work for me without on-load with just yo-yoify for some reason: transloadit/uppy@037b64b.

I think this is because it was still installed by the previous build through https://github.com/transloadit/uppy/blob/master/.travis.yml#L17-L19 btw

**Comment by arturi** [comment]
Might be, yes. I cleared cache a few times, but not for that build.
