### ISSUE TITLE
Issues with svg

### ISSUE THREAD

**Issue by graforlock** [goto-bus-stop/babel-plugin-yo-yoify#21]
When it comes to processing SVGs `yo-yoify` the output is empty in the browser.

Svg tag is there physically but its being done incorrectly (I presume so) as it results in blank boxes.

**Comment by goto-bus-stop** [comment]
svgs work for us in [uppy](https://github.com/transloadit/uppy) with this plugin, but something may be missing still. could you share a small example that shows the problem? thanks!

**Comment by graforlock** [comment]
Hey, sorry its been a while, so it seems that:

1). It strips off `xmlns` declaration from `use` tags
2). Adds it to `svg` where normally `bel` removes it.

Example: 

- without the plugin, just `bel`:
```
<svg viewBox="0 -5 31 41" class="icon">
  <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#full-star"></use>
</svg>
```

- with the plugin, with `yo-yoify` in .babelrc:
```
<svg viewBox="0 -5 31 41" class="icon" 
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <use xlink:href="#full-star"></use>
</svg>
```

-----

Thats the difference. I think `use` without xmlns declaration is the main offender here.

**Comment by goto-bus-stop** [comment]
I believe this is getting fixed in nanohtml by https://github.com/choojs/nanohtml/pull/123!
