### ISSUE TITLE
`useImport` option no longer works?

### ISSUE THREAD

**Issue by saulhardman** [goto-bus-stop/babel-plugin-yo-yoify#22]
Despite using the `{ "useImport": true }` option in my `.babelrc`, a `require()` statement is added instead of an `import`.

Did this functionality get lost somewhere along the way?

#### Reproduction

Source: https://glitch.com/edit/#!/spring-tune?path=server.js
Output: https://spring-tune.glitch.me/

Thanks in advance.

**Comment by goto-bus-stop** [comment]
oops, you're right, i must've accidentally removed it. thanks for the report! added back in 📦 1.0.2

**Comment by saulhardman** [comment]
Hi @goto-bus-stop, thanks for the response and quick fix. I can confirm that it's working on my end 👍
