### ISSUE TITLE
TypeError: Function.caller used to retrieve strict caller when using onload

### ISSUE THREAD

**Issue by arturi** [goto-bus-stop/babel-plugin-yo-yoify#9]
Thanks for your work, love this transform! Exactly what I needed for http://github.com/transloadit/uppy. I recently created an issue asking if using yo-yoify as a Babel transform was possible https://github.com/shama/bel/issues/65, then made [yo-yoify-standalone](https://github.com/arturi/yo-yoify-standalone/tree/master), which just wraps original yo-yoify and pipes the parsed version out. And then stumbled upon your babel-plugin-yo-yoify :)

The [issue mentioned here](https://github.com/shama/bel#note), which is resolved by original yo-yoify browserify transform, however, remains: I get `TypeError: Function.caller used to retrieve strict caller` (in Safari) when running a bundle where `onload` has been used on an element. 

I’ve noticed you are parsing onload attributes somehow, but can’t figure out what how exactly yo-yoify “transforms any Function.caller into plain strings”.

<img width="1237" alt="screen shot 2017-02-26 at 10 45 26 pm" src="https://cloud.githubusercontent.com/assets/1199054/23348114/4f4c53b6-fc75-11e6-8265-4db5e138cea8.png">

**Comment by goto-bus-stop** [comment]
Thanks for the report! Turns out there's an undocumented parameter in on-load that can be used to identify elements, so now babel-plugin-yo-yoify will pass a unique ID into it for each different element.

**Comment by arturi** [comment]
Thank you!
